### ISSUE TITLE
panic :wrong theme name

### ISSUE THREAD

**Issue by liaoyinyu** [GoAdminGroup/demo.go-admin.cn#1]
当我运行 
`go run main.go`
出现以下错误
`goroutine 1 [running]:
github.com/GoAdminGroup/go-admin/template.Get(0xefe185, 0x8, 0x17, 0xc4204b5150)
	/home/liaoyinyu/workspace/go_ws/src/github.com/GoAdminGroup/go-admin/template/template.go:67 +0x96
github.com/GoAdminGroup/go-admin/plugins/admin.InitRouter(0xc42042da2a, 0x6, 0xfdbcc0)
	/home/liaoyinyu/workspace/go_ws/src/github.com/GoAdminGroup/go-admin/plugins/admin/router.go:26 +0x45b
github.com/GoAdminGroup/go-admin/plugins/admin.(*Admin).InitPlugin(0x17328e0)
	/home/liaoyinyu/workspace/go_ws/src/github.com/GoAdminGroup/go-admin/plugins/admin/admin.go:30 +0x1bf
github.com/GoAdminGroup/go-admin/engine.(*Engine).AddPlugins(0xc4204b5dc8, 0xc4204b5db8, 0x1, 0x1, 0xc42042da20)
	/home/liaoyinyu/workspace/go_ws/src/github.com/GoAdminGroup/go-admin/engine/engine.go:43 +0x45
main.main()
	/home/liaoyinyu/workspace/go_ws/src/go_admin/demo.go-admin.cn/main.go:52 +0x2aa
`

**Comment by chenhg5** [comment]
@liaoyinyu 将```import```中```github.com/GoAdminGroup/themes/sword```改为```github.com/GoAdminGroup/themes/adminlte```，详细请参考：http://www.go-admin.cn/docs/#/admin/theme

**Comment by liaoyinyu** [comment]
好了，thank you
