### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by xiaomi-tc** [GoAdminGroup/demo.go-admin.cn#2]
下载后，在本地mysql 里导入 admin.sql , 修改 main.go里的配置文件路径和配置文件名， 本地(centos7) 编译后运行，出来登录界面，但登录不进系统
`

    //rootPath := "/data/www/go-admin"
    rootPath := "."

    cfg := config.ReadFromJson(rootPath + "/config.json")`

mysql 内容：
mysql> use go_admin_demo;
...
Database changed
mysql> show tables;
+--------------------------+
| Tables_in_go_admin_demo  |
+--------------------------+
| authors                  |
| goadmin_menu             |
| goadmin_operation_log    |
| goadmin_permissions      |
| goadmin_role_menu        |
| goadmin_role_permissions |
| goadmin_role_users       |
| goadmin_roles            |
| goadmin_session          |
| goadmin_user_permissions |
| goadmin_users            |
| posts                    |
| users                    |
+--------------------------+
13 rows in set (0.01 sec)

**Comment by chenhg5** [comment]
@xiaomi-tc 将配置中的domain删了试试

**Comment by xiaomi-tc** [comment]
可以了，多谢！
